# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: 'AutomatedRelease'
      - name: Setup
        run: |
            apt-get update -qy && apt-get -y install git
            git config --global user.name 'GITHUB Automated Builder'
            git config --global user.email 'contact@buildit-consulting.de'
            git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/$GITHUB_REPOSITORY
            echo "CURRENTDATE=$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
      - run: npm ci
      - name: condition 1
        if: "contains(github.event.head_commit.message, 'Release')"
        run: npm version patch

      - name: condition 2
        if: "contains(github.event.head_commit.message, 'Major Release')"
        run: npm version major
        
      - name: condition 2
        if: "contains(github.event.head_commit.message, 'Minor Release')"
        run: npm version minor 
      - run: npm run build
      - run: echo "VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
      - name: Upload
        run: |
            git add .
            git commit -m "AutomatedRelease ${{ env.CURRENTDATE }}"
            git push origin ${{ env.VERSION }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
