name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: 'AutomatedRelease'
      - name: Setup
        run: |
            apt-get update -qy && apt-get -y install git
            git config --global user.name 'GITHUB Automated Builder'
            git config --global user.email 'contact@buildit-consulting.de'
            git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/$GITHUB_REPOSITORY
            echo "CURRENTDATE=$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
      - run: npm ci
      - run: git add ./bin/createPlugin.js
      - name: Patch Version
        run: npm version patch -m "AutomatedRelease - Upgrade to %s"
      - name: Major Verison
        if: "contains(github.event.head_commit.message, 'Major Release')"
        run: npm version major -m "AutomatedRelease - Upgrade to %s"
      - name: Minor Version
        if: "contains(github.event.head_commit.message, 'Minor Release')"
        run: npm version minor -m "AutomatedRelease - Upgrade to %s"
      - run: npm run build
      - run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Upload
        run: |
            git push origin main
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}        
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
